import { test,expect, type Page } from '@playwright/test';
import { mkdir,readFile } from 'node:fs/promises';
import { createClient } from '@supabase/supabase-js';
async function nav(page:Page,name:string){const menu=page.getByRole('button',{name:'Open navigation'});if(await menu.isVisible())await menu.click();await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name,exact:true}).click();}
test('city markers open CITY details; explicit add; keyboard and phone layout',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/preview');
 await expect(page.getByText('Preview · no live data imported')).toBeVisible();
 const marker=page.getByRole('button',{name:'Explore city Quincy, IL',exact:true});await marker.scrollIntoViewIfNeeded();await marker.focus();await page.keyboard.press('Enter');
 const panel=page.getByTestId('city-panel');await expect(panel.getByRole('heading',{name:'Quincy, IL',exact:true})).toBeVisible();await expect(page.locator('main')).toHaveAttribute('data-tab','Explore');await expect(panel.getByText('No verified food records. Cuisine is not halal verification.')).toBeVisible();
 await mkdir('test-results/evidence',{recursive:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);await page.screenshot({path:'test-results/evidence/'+info.project.name+'-city.png',fullPage:true});
 await panel.getByRole('button',{name:'Add to trip',exact:true}).click();await expect(page.locator('main')).toHaveAttribute('data-tab','Trips');await expect(page.getByRole('heading',{name:'Quincy, IL',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Add store or event',exact:true}).click();await page.getByRole('button',{name:'Add store or event',exact:true}).click();await expect(page.getByText(/2 store\/event stops/)).toBeVisible();
 await page.getByRole('button',{name:'Move Unconfirmed source down'}).first().click();await page.getByRole('button',{name:'Calculate road route'}).click();await expect(page.getByText('Route unavailable: sign in and configure Mapbox Directions.')).toBeVisible();
 await expect(page.locator('.route-map-canvas svg path[stroke="#304b3c"]')).toHaveCount(0);
 await page.screenshot({path:'test-results/evidence/'+info.project.name+'-trip.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);expect(overflow).toBe(false);expect(errors).toEqual([]);
});
test('all night presets, solo crew and impossible two-city days stay explicit',async({page},info)=>{
 await page.goto('/preview');await page.getByRole('button',{name:'New trip',exact:true}).first().click();
 for(const [label,count] of [['Day trip',1],['2 days / 1 night',2],['3 days / 2 nights',3],['4 days / 3 nights',4]] as const){await page.getByLabel(label,{exact:true}).check();await expect(page.getByRole('tablist',{name:'Trip days'}).getByRole('tab')).toHaveCount(count);}
 await page.getByRole('tablist').getByRole('tab').nth(2).click();await expect(page.getByRole('heading',{name:'Night 3 · overnight lodging'})).toBeVisible();
 await page.getByLabel('Kerem',{exact:true}).uncheck();await expect(page.getByLabel('Naim',{exact:true})).toBeChecked();await expect(page.getByLabel('Kerem',{exact:true})).not.toBeChecked();
 await page.getByRole('tablist').getByRole('tab').first().click();await page.getByLabel('Add a sourcing city').selectOption('rolla-mo');await page.getByLabel('Add a sourcing city').selectOption('springfield-mo');await page.getByLabel('Shared city sourcing window (hours)').nth(1).fill('10');await expect(page.locator('.schedule-status')).toContainText('Infeasible');await expect(page.getByLabel('Shared city sourcing window (hours)').nth(1)).toHaveValue('10');await page.screenshot({path:'test-results/evidence/'+info.project.name+'-multi-night.png',fullPage:true});
});
test('private base editor confirms no guessed address and focus returns',async({page})=>{
 await page.goto('/preview');await page.getByRole('button',{name:'Edit base',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Actual address')).toHaveValue('');await expect(dialog.getByLabel('Latitude')).toHaveValue('38.55');await expect(dialog.getByLabel('I confirm this exact access pin')).not.toBeChecked();await dialog.getByRole('button',{name:'Close dialog'}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('button',{name:'Edit base',exact:true})).toBeFocused();
});
test('measured text, controls, focus and markers meet contrast thresholds',async({page})=>{
 await page.goto('/preview');
 const ratios=await page.evaluate(()=>{const lum=(s:string)=>{const rgb=(s.match(/[\d.]+/g)||[]).slice(0,3).map(Number).map(v=>{const x=v/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;});return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];};const ratio=(a:string,b:string)=>{const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);};const root=getComputedStyle(document.documentElement),paper=root.getPropertyValue('--paper');const asRGB=(color:string)=>{const el=document.createElement('span');el.style.color=color;document.body.append(el);const c=getComputedStyle(el).color;el.remove();return c;};const results:Record<string,number>={};for(const name of ['--ink','--muted','--green','--rust'])results[name]=ratio(asRGB(root.getPropertyValue(name)),asRGB(paper));for(const name of ['--border','--focus'])results[name]=ratio(asRGB(root.getPropertyValue(name)),asRGB(paper));const marker=document.querySelector<SVGCircleElement>('.map-marker circle:last-of-type')!;results.marker=ratio(asRGB(marker.getAttribute('fill')!),asRGB(root.getPropertyValue('--map')));return results;});
 expect(ratios['--ink']).toBeGreaterThanOrEqual(4.5);expect(ratios['--muted']).toBeGreaterThanOrEqual(4.5);expect(ratios['--green']).toBeGreaterThanOrEqual(4.5);expect(ratios['--rust']).toBeGreaterThanOrEqual(4.5);expect(ratios['--border']).toBeGreaterThanOrEqual(3);expect(ratios['--focus']).toBeGreaterThanOrEqual(3);expect(ratios.marker).toBeGreaterThanOrEqual(3);
 const search=page.getByRole('textbox',{name:'Search cities'});await search.focus();expect(await search.evaluate(el=>getComputedStyle(el).outlineWidth)).toBe('3px');
});
test('real login, saves across reload and another member/device; denied outsider APIs',async({page,browser},info)=>{
 let fixture:{url:string;key:string;workspaceId:string;cityId:string;users:{label:string;email:string;password:string}[]};try{fixture=JSON.parse(await readFile('private/qa-users.json','utf8'));}catch{test.skip(true,'Run retained isolated test:auth stack first; real auth is unverified without it.');return;}
 const owner=fixture.users.find(u=>u.label==='owner')!,partner=fixture.users.find(u=>u.label==='partner')!,outsider=fixture.users.find(u=>u.label==='outsider')!;
 await page.goto('/sign-in');await page.getByLabel('Email',{exact:true}).fill(owner.email);await page.getByLabel('Password',{exact:true}).fill(owner.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText(/Private Fieldwork workspace/)).toBeVisible();
 await page.getByRole('button',{name:'New trip',exact:true}).first().click();const name='Synthetic QA trip '+info.project.name+' '+Date.now();await page.getByLabel('Trip name',{exact:true}).fill(name);await page.getByLabel('Add a sourcing city').selectOption(fixture.cityId);await page.getByRole('button',{name:'Add store or event',exact:true}).click();await page.getByRole('button',{name:'Save trip',exact:true}).click();await expect(page.getByText(/Trip persisted to the shared workspace/)).toBeVisible();
 await page.reload();await nav(page,'Trips');await page.getByLabel('Open saved trip').selectOption({label:name});await expect(page.getByLabel('Trip name')).toHaveValue(name);await expect(page.getByText(/1 store\/event stops/)).toBeVisible();
 await nav(page,'Explore');const cityButton=page.locator('button[data-cityid="'+fixture.cityId+'"]');await cityButton.click();const panel=page.getByTestId('city-panel');await panel.getByLabel('City note',{exact:true}).fill('Synthetic shared note '+name);await panel.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByText('City note saved to the workspace.')).toBeVisible();
 await page.screenshot({path:'test-results/evidence/'+info.project.name+'-authenticated.png',fullPage:true});
 const context=await browser.newContext({viewport:info.project.name==='phone'?{width:1440,height:900}:{width:390,height:844}});try{const second=await context.newPage();await second.goto('/sign-in');await second.getByLabel('Email',{exact:true}).fill(partner.email);await second.getByLabel('Password',{exact:true}).fill(partner.password);await second.getByRole('button',{name:'Sign in',exact:true}).click();await expect(second.getByText(/Private Fieldwork workspace/)).toBeVisible();await nav(second,'Trips');await second.getByLabel('Open saved trip').selectOption({label:name});await expect(second.getByLabel('Trip name')).toHaveValue(name);}finally{await context.close();}
 const client=createClient(fixture.url,fixture.key,{auth:{persistSession:false}});const signed=await client.auth.signInWithPassword({email:outsider.email,password:outsider.password});expect(signed.error).toBeNull();const token=signed.data.session!.access_token;
 const denied=await page.request.get('/api/workspaces/'+fixture.workspaceId+'/data',{headers:{Authorization:'Bearer '+token}});expect(denied.status()).toBe(403);
 const deniedWrite=await page.request.post('/api/workspaces/'+fixture.workspaceId+'/notes',{headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},data:{city_id:fixture.cityId,body:'Must never persist',mutation_key:crypto.randomUUID()}});expect(deniedWrite.status()).toBe(403);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.getByRole('heading',{name:'Back to the field.'})).toBeVisible();
});

test('synthetic provider response renders round-trip geometry, city hit priority and stale-response protection',async({page})=>{
 let fixture:{url:string;key:string;workspaceId:string;cityId:string;users:{id:string;label:string;email:string;password:string}[]};try{fixture=JSON.parse(await readFile('private/qa-users.json','utf8'));}catch{test.skip(true,'Retained real-auth fixture unavailable.');return;}
 const {readyTrip,testPoint}=await import('../helpers/fixtures');const {routeRevision}=await import('../../src/lib/routing/revision');const {routeWaypoints}=await import('../../src/lib/planning/schedule');
 const owner=fixture.users.find(u=>u.label==='owner')!,client=createClient(fixture.url,fixture.key,{auth:{persistSession:false}}),login=await client.auth.signInWithPassword({email:owner.email,password:owner.password});expect(login.error).toBeNull();
 const trip=readyTrip();trip.id=crypto.randomUUID();trip.name='Synthetic route QA '+Date.now();trip.participants=[owner.id];trip.transport.vehicleIds=[];trip.transport.driverAssignments=[];trip.days[0].visits[0].cityId=fixture.cityId;trip.days[0].visits[0].cityName='Synthetic QA city';const s=trip.days[0].visits[0].stops[0];s.name='Synthetic A';s.id=crypto.randomUUID();s.point={...testPoint('a'),lng:-90.95,lat:38.54};trip.days[0].visits[0].stops.push({...s,id:crypto.randomUUID(),name:'Synthetic B',point:{...testPoint('b'),lng:-90.9,lat:38.6}});
 const saved=await page.request.post('/api/workspaces/'+fixture.workspaceId+'/trips',{headers:{Authorization:'Bearer '+login.data.session!.access_token,'Content-Type':'application/json'},data:trip});expect(saved.status()).toBe(200);
 await page.goto('/sign-in');await page.getByLabel('Email',{exact:true}).fill(owner.email);await page.getByLabel('Password',{exact:true}).fill(owner.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText(/Private Fieldwork workspace/)).toBeVisible();await nav(page,'Trips');await page.getByLabel('Open saved trip').selectOption({label:trip.name});
 let count=0;await page.route('**/api/workspaces/*/routes',async route=>{const draft=route.request().postDataJSON();const points=routeWaypoints(draft);count++;const invocation=count;await new Promise(r=>setTimeout(r,invocation===2?1400:100));try{await route.fulfill({json:{status:'available',revision:routeRevision(draft),reason:null,legs:points.slice(1).map((w,i)=>({from:points[i].point.id,to:w.point.id,seconds:600,meters:invocation===2?1609.344*99:1609.344*6,geometry:[[points[i].point.lng,points[i].point.lat],[(points[i].point.lng+w.point.lng)/2+.005,(points[i].point.lat+w.point.lat)/2-.003],[w.point.lng,w.point.lat]],kind:w.kind,provider:'mapbox',fetchedAt:new Date().toISOString()}))}});}catch{/* aborted stale requests are expected */}});
 await page.getByRole('button',{name:'Calculate road route'}).click();await expect(page.getByText('Mapbox driving geometry · typical/static estimate')).toBeVisible();await expect(page.locator('.road-summary .leg-row')).toHaveCount(3);await expect(page.locator('.route-map-canvas path[stroke="#994a2f"]')).toHaveCount(1);
 await page.getByRole('button',{name:'Move Synthetic A down'}).click();await expect.poll(()=>count).toBe(2);await page.getByRole('button',{name:'Move Synthetic A up'}).click();await expect.poll(()=>count).toBe(3);await expect(page.locator('.road-summary')).toContainText('6.0 road miles');await page.waitForTimeout(1550);await expect(page.locator('.road-summary')).not.toContainText('99.0 road miles');
 const marker=page.locator('.route-map-canvas').getByRole('button',{name:'Explore city Synthetic QA city, XX',exact:true});await marker.focus();await page.keyboard.press('Enter');await expect(page.getByTestId('city-panel').getByRole('heading',{name:'Synthetic QA city, XX'})).toBeVisible();await expect(page.locator('main')).toHaveAttribute('data-tab','Explore');
});
