import { test, expect, type Page } from "@playwright/test";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { readFile } from "node:fs/promises";
const evidence = process.env.FIELDWORK_EVIDENCE_DIR || tmpdir();
async function selectRolla(page: Page) {
  await page.locator('[data-city-id="rolla"]').waitFor();
  if (await page.locator('.mobile-search').isVisible()) await page.locator('.mobile-search button').click();
  await page.getByRole('textbox', { name: 'Search routes or places', exact: true }).filter({ visible: true }).fill('Rolla');
  await page.locator('.place-results button').filter({ hasText: 'Rolla, MO' }).filter({ visible: true }).click();
  await expect(page.getByTestId('original-city-panel').getByRole('heading', { name: 'Rolla, MO', exact: true })).toBeVisible();
}
test('restored source identity, assets and all catalog markers render without errors', async ({ page }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/');
  await expect(page).toHaveTitle('Fieldwork · Book sourcing');
  await expect(page.locator('.wordmark')).toHaveText('Fieldwork');
  await expect(page.getByText('Saved on this device', { exact: true })).toBeVisible();
  await expect(page.locator('.leaflet-marker-pane [data-city-id]')).toHaveCount(109);
  await page.evaluate(() => document.fonts.ready);
  const style = await page.locator('.fieldwork-app').evaluate(element => ({ font: getComputedStyle(element).fontFamily, color: getComputedStyle(element).color, background: getComputedStyle(element).backgroundColor, overflow: document.documentElement.scrollWidth > innerWidth }));
  expect(style).toMatchObject({ background: 'rgb(250, 248, 243)', color: 'rgb(37, 53, 44)', overflow: false });
  expect(style.font).toContain('Manrope');
  await page.screenshot({ path: join(evidence, `fieldwork-${info.project.name}-map.png`), animations: 'disabled' });
  await page.getByRole('tab', { name: 'Routes', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'Routes', exact: true })).toHaveAttribute('data-state', 'active');
  await expect(page.locator('.corridor-table tbody tr')).toHaveCount(15);
  await expect(page.locator('.mobile-corridors article')).toHaveCount(15);
  await page.getByRole('textbox', { name: 'Search corridors' }).fill('Rolla');
  await expect(page.locator('.mobile-corridors article')).toHaveCount(1);
  await page.getByRole('textbox', { name: 'Search corridors' }).fill('');
  await page.screenshot({ path: join(evidence, `fieldwork-${info.project.name}-routes.png`), animations: 'disabled' });
  expect(errors).toEqual([]);
});
test('city selection stays separate from trip creation, with keyboard marker access', async ({ page }, info) => {
  const unsafe: string[] = [];
  page.on('request', request => { if (request.url().includes('/api/records') || (request.method() !== 'GET' && request.url().includes('/api/workspaces/'))) unsafe.push(request.url()); });
  await page.goto('/');
  await selectRolla(page);
  const city = page.getByTestId('original-city-panel');
  await expect(city.getByText('Untested · no visit observations')).toBeVisible();
  await expect(city.getByText(/awaiting three scored visits/)).toBeVisible();
  await page.screenshot({ path: join(evidence, `fieldwork-${info.project.name}-city.png`), animations: 'disabled' });
  await city.getByRole('button', { name: 'Close place details' }).click();
  const marker = page.getByRole('button', { name: 'Explore city Rolla, MO', exact: true });
  await marker.focus();
  await page.keyboard.press('Enter');
  await expect(city.getByRole('heading', { name: 'Rolla, MO', exact: true })).toBeFocused();
  await city.getByRole('button', { name: 'Add city to trip', exact: true }).click();
  const planner = page.getByRole('dialog');
  await expect(planner.getByRole('heading', { name: 'Plan a sourcing trip' })).toBeVisible();
  await expect(planner.locator('.planner-stop')).toHaveCount(1);
  await expect(planner.locator('.planner-stop')).toContainText('Rolla');
  await planner.getByLabel('Trip name', { exact: true }).fill('Synthetic saved trip');
  await planner.getByText('Record actual route economics', { exact: true }).click();
  await expect(planner.getByLabel('Realized book profit after acquisition and fees ($)', { exact: true })).toHaveValue('');
  await planner.getByLabel('Realized book profit after acquisition and fees ($)', { exact: true }).fill('500');
  await planner.getByLabel('Actual fuel, tolls, lodging and other travel ($)', { exact: true }).fill('96');
  await planner.getByLabel('Actual processing costs ($)', { exact: true }).fill('0');
  await planner.getByLabel('Actual sourcing labor costs ($)', { exact: true }).fill('0');
  await planner.getByLabel('Actual door-to-door hours', { exact: true }).fill('8');
  await planner.getByRole('button', { name: 'Save trip', exact: true }).click();
  await expect(planner).not.toBeVisible();
  await page.getByRole('tab', { name: 'Insights', exact: true }).click();
  await expect(page.locator('.actual-economics')).toContainText('$404.00 recorded actual route profit');
  await expect(page.locator('.actual-economics')).toContainText('$50.50 / trip hour');
  expect(unsafe).toEqual([]);
  await page.reload();
  await page.getByRole('tab', { name: 'Trips', exact: true }).click();
  await expect(page.getByText('Synthetic saved trip', { exact: true })).toBeVisible();
});
test('zero outcomes and raw quality survive navigation and reload; saturation waits for three visits', async ({ page }, info) => {
  await page.goto('/');
  await selectRolla(page);
  for (const score of [4, 6, 8]) {
    await page.getByTestId('original-city-panel').getByRole('button', { name: /Log visit in Rolla/ }).click();
    const form = page.getByRole('dialog');
    await form.getByLabel('Source name', { exact: true }).fill('Synthetic zero-book source');
    await form.getByLabel('Books scanned (optional)', { exact: true }).fill('0');
    await form.getByLabel('Scanner competitors observed', { exact: true }).fill('0');
    await form.getByLabel('Saturation observed after this visit', { exact: true }).selectOption(String(score));
    await form.getByText('Source quality: raw evidence and optional 0–5 scores', { exact: true }).click();
    await form.getByLabel('volume — raw observation', { exact: true }).fill('Four full shelves observed; no suitable buys');
    await form.getByLabel('volume — score', { exact: true }).selectOption('4');
    await form.getByRole('button', { name: 'Save visit', exact: true }).click();
    await expect(form).not.toBeVisible();
    if (score < 8) await expect(page.getByTestId('original-city-panel').getByText(/awaiting three scored visits/)).toBeVisible();
  }
  await expect(page.getByTestId('original-city-panel').getByText(/Observed saturation: 6.0 \/ 10 across 3 scored visits/)).toBeVisible();
  await page.getByRole('tab', { name: 'Insights', exact: true }).click();
  const row = page.locator('.comparison-table tbody tr').filter({ hasText: 'I-44 technical corridor' });
  await expect(row).toContainText('6.0 / 10');
  await expect(page.locator('.yield-rows')).toContainText('100% zero-book stops');
  await page.getByText('Raw visit observations', { exact: true }).click();
  await expect(page.locator('.raw-observations')).toContainText('Four full shelves observed; no suitable buys (4 / 5)');
  await page.screenshot({ path: join(evidence, `fieldwork-${info.project.name}-observations.png`), animations: 'disabled' });
});
test('recovered lead details are unverified and source class filters respond', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('tab', { name: 'Routes', exact: true }).click();
  await page.getByLabel('Inventory class', { exact: true }).selectOption('1');
  await expect(page.locator('.source-rows .source-row')).toHaveCount(2);
  await page.getByLabel('Inventory class', { exact: true }).selectOption('2');
  await expect(page.locator('.source-rows .source-row')).toHaveCount(4);
  await page.locator('.source-row').filter({ hasText: 'Quincy Friends fall book sale' }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByText(/Recovered details, prices and sale dates are historical claims/)).toBeVisible();
  await expect(dialog.getByLabel('Details last checked', { exact: true })).toHaveValue('');
  await expect(dialog.getByLabel('ISBN scanning', { exact: true })).toHaveValue('Unknown');
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
});
test('saved status changes, linked visits, trip removal and exports keep a coherent record', async ({ page }) => {
  await page.goto('/');
  await selectRolla(page);
  await page.getByTestId('original-city-panel').getByRole('button', { name: 'Add city to trip', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Trip name', { exact: true }).fill('Synthetic removable trip');
  await page.getByRole('dialog').getByRole('button', { name: 'Save trip', exact: true }).click();
  await page.getByRole('tab', { name: 'Trips', exact: true }).click();
  const card = page.locator('.trip-item').filter({ hasText: 'Synthetic removable trip' });
  await card.getByRole('button', { name: 'Start trip', exact: true }).click();
  await expect(card.locator('.trip-status')).toHaveText('On the road');
  await card.getByRole('button', { name: 'Log visit', exact: true }).click();
  const visit = page.getByRole('dialog');
  await visit.getByLabel('Source name', { exact: true }).fill('Synthetic linked source');
  await visit.getByLabel('Books bought', { exact: true }).fill('2');
  await visit.getByLabel('Book purchase cost ($)', { exact: true }).fill('1');
  await visit.getByRole('button', { name: 'Save visit', exact: true }).click();
  await card.getByRole('button', { name: 'More actions for Synthetic removable trip', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Remove trip', exact: true }).click();
  await page.getByRole('alertdialog').getByRole('button', { name: 'Remove entry', exact: true }).click();
  await expect(card).toHaveCount(0);
  await page.getByRole('button', { name: 'Workspace settings', exact: true }).click();
  const settings = page.getByRole('dialog');
  await expect(settings.getByText(/survive reloads/)).toBeVisible();
  const downloaded = page.waitForEvent('download');
  await settings.getByRole('button', { name: 'Backup JSON', exact: true }).click();
  const download = await downloaded;
  const data = JSON.parse(await readFile((await download.path())!, 'utf8'));
  expect(data.persistence).toBe('browser-local');
  expect(data.records.filter((record: { kind: string }) => record.kind === 'trip')).toHaveLength(0);
  const observations = data.records.filter((record: { kind: string }) => record.kind === 'visit');
  expect(observations).toHaveLength(1);
  expect(observations[0].data).toMatchObject({ books: 2, spend: 1, tripId: null, sourceName: 'Synthetic linked source' });
});
