"use client";
import { useEffect, useRef, useState } from 'react';
import { Search, Utensils, Clock, Car, Plus, X, MapPin } from 'lucide-react';
import type { City, WorkspaceData, Source, SourceEvent } from '@/lib/model';
import type { CityEstimate } from '@/lib/routing/city-estimate';
import { displayTime } from '@/lib/planning/time';
function miles(a:City,b:City){if(a.lat===null||a.lng===null||b.lat===null||b.lng===null)return Infinity;const rad=(x:number)=>x*Math.PI/180;const dlat=rad(b.lat-a.lat),dlng=rad(b.lng-a.lng);return 3958.8*2*Math.asin(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlng/2)**2));}
export default function CityPanel({city,data,preview,onAdd,onClose,onSource,onNewSource,onNewEvent,onExplore,onNote,targetDay}:{city:City;data:WorkspaceData;preview:boolean;onAdd:()=>void;onClose:()=>void;onSource:(s:Source,e?:SourceEvent)=>void;onNewSource:()=>void;onNewEvent:()=>void;onExplore:(c:City)=>void;onNote:(body:Record<string,unknown>)=>Promise<void>;targetDay:number}){
 const sources=data.sources.filter(s=>s.city_id===city.id),eligible=sources.filter(s=>s.category!=='regular_goodwill'&&s.category!=='half_price_books'),food=data.food.filter(f=>f.city_id===city.id),visits=data.visits.filter(v=>v.city_id===city.id),notes=data.notes.filter(n=>n.city_id===city.id),events=data.events.filter(e=>sources.some(s=>s.id===e.source_id));
 const nearby=data.cities.filter(c=>c.id!==city.id&&miles(c,city)<100).sort((a,b)=>miles(a,city)-miles(b,city));
 const [estimate,setEstimate]=useState<CityEstimate|null>(null),[note,setNote]=useState(''),[noteError,setNoteError]=useState(''),[busy,setBusy]=useState(false),[mutation,setMutation]=useState(()=>crypto.randomUUID());
 const [checkedOn]=useState(()=>Date.now());
 const title=useRef<HTMLHeadingElement>(null),panel=useRef<HTMLElement>(null);
 useEffect(()=>{const controller=new AbortController();if(!preview&&data.workspaceId)void fetch('/api/workspaces/'+data.workspaceId+'/city-estimate?city='+city.id,{cache:'no-store',signal:controller.signal}).then(async r=>{const value=await r.json();if(!controller.signal.aborted)setEstimate(r.ok?value:{status:'unavailable',minutes:null,miles:null,reason:value.error||'Route unavailable.',fetchedAt:null});}).catch(()=>{});return()=>controller.abort();},[city.id,data.workspaceId,data.origin,preview]);
 useEffect(()=>{if(window.matchMedia('(max-width:900px)').matches)title.current?.focus();},[city.id]);
 return <aside ref={panel} className="city-panel" aria-label="City details" data-testid="city-panel" onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'&&window.matchMedia('(max-width:900px)').matches){const controls=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],textarea,input');const first=controls?.[0],last=controls?.[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
  <div className="panel-title"><h2 ref={title} tabIndex={-1}>{city.name}, {city.state}</h2><button className="icon-button mobile-only" aria-label="Close city panel" onClick={onClose}><X size={20}/></button></div><p>{city.overview||'No sourced overview yet.'}</p><p className="secondary">{city.provenance||'Workspace reference · verification needed'}</p>
  <div className="city-detail-content">
  <section><h3><Search size={20}/>Sourcing opportunities</h3>{eligible.length?<ul className="detail-list">{eligible.map(s=><li key={s.id}><strong>{s.name}</strong><span>{s.is_lead?'Unconfirmed lead · not store navigation':s.category.replaceAll('_',' ')}</span>{s.point&&<span>{s.point.address||'Access address unknown'}</span>}<span>{s.checked_at?'Checked '+s.checked_at.slice(0,10)+(checkedOn-Date.parse(s.checked_at)>90*86400000?' · stale (over 90 days); recheck':''):'Hours / pricing unverified'}</span>{s.evidence_url?.startsWith('https://')&&<a href={s.evidence_url} target="_blank" rel="noreferrer">Source evidence</a>}<button className="text-button" onClick={()=>onSource(s)}>Add this source explicitly</button></li>)}</ul>:<p>No verified stores or events yet.</p>}{sources.length>eligible.length&&<p className="secondary">Regular Goodwill retail and Half Price Books are excluded. Trip exceptions must be explicit.</p>}
   {events.length>0&&<ul className="detail-list">{events.map(e=><li key={e.id}><strong>{e.name}</strong><span>{e.windows?.map(w=>w.start+' → '+w.end).join('; ')||'Dates/windows unconfirmed'}</span><span>{e.checked_at?'Checked '+e.checked_at.slice(0,10):'Not checked'}</span>{e.evidence_url&&<a href={e.evidence_url} target="_blank" rel="noreferrer">Event source</a>}{sources.find(s=>s.id===e.source_id)&&<button className="text-button" onClick={()=>onSource(sources.find(s=>s.id===e.source_id)!,e)}>Add this event explicitly</button>}</li>)}</ul>}
   <button className="text-button" onClick={onNewSource}><Plus size={16}/>Record a source or lead</button><button className="text-button" onClick={onNewEvent}>Record a dated event</button>
  </section>
  {nearby.length>0&&<section><h3><MapPin size={20}/>Nearby references</h3><p className="secondary">Within roughly 100 geographic miles; road times and sourcing value require verification.</p>{nearby.slice(0,4).map(c=><button className="text-button" key={c.id} onClick={()=>onExplore(c)}>{c.name}, {c.state} · {data.sources.filter(s=>s.city_id===c.id).length} recorded leads/sources</button>)}</section>}
  <section><h3><Utensils size={20}/>Halal food</h3>{food.length?<ul className="detail-list">{food.map(f=><li key={f.id}><strong>{f.name}</strong><span>{f.status.replaceAll('_',' ')} · {f.checked_at?'checked '+f.checked_at.slice(0,10)+(checkedOn-Date.parse(f.checked_at)>90*86400000?' · stale; recheck':''):'date unknown'}</span>{f.point?.address&&<span>{f.point.address}</span>}<span>{f.scope||'Scope unconfirmed'}</span>{f.evidence_url?.startsWith('https://')&&<a href={f.evidence_url} target="_blank" rel="noreferrer">Verification source</a>}</li>)}</ul>:<p>No verified food records. Cuisine is not halal verification.</p>}</section>
  <section><h3><Clock size={20}/>Visit history</h3>{visits.length?<ul className="detail-list">{visits.map(v=><li key={v.id}><strong>{new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeZone:city.zone}).format(new Date(v.visited_at))} · {displayTime(v.visited_at,city.zone)}</strong><span>{v.bought===null?'Books bought unknown':v.bought+' books bought'} · {v.usable===null?'usable unknown':v.usable+' usable'}</span><p>{v.notes}</p></li>)}</ul>:<p>{preview?'No imported visits.':'No visits recorded. This opportunity is untested.'}</p>}{notes.map(n=><p key={n.id} className="city-note">{n.body}</p>)}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setNoteError('');try{await onNote({city_id:city.id,body:note,mutation_key:mutation});setNote('');setMutation(crypto.randomUUID());}catch(err){setNoteError(err instanceof Error?err.message:'Not saved.');}finally{setBusy(false);}}}><label>City note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={20000}/></label><button className="secondary-button" disabled={preview||busy||!note.trim()}>{busy?'Saving…':'Save note'}</button></form>{noteError&&<p role="alert">{noteError}</p>}</section>
  <section><h3><Car size={20}/>Driving time</h3><p>{estimate?.status==='available'?Math.round(estimate.minutes!)+' minutes · '+estimate.miles!.toFixed(1)+' road miles':'Route unavailable.'}</p><p className="secondary">{estimate?.reason||'Confirm the private base and routing provider. City estimates are approximate; a ready trip uses exact store addresses.'}{estimate?.fetchedAt?' · calculated '+new Date(estimate.fetchedAt).toLocaleString():''}</p></section>
  </div>
  <div className="city-actions"><p className="secondary">Add to Day {targetDay} of the current draft.</p><button className="primary add-city" onClick={onAdd}><Plus size={18}/>Add to trip</button></div>
 </aside>;
}
