import type { City, Corridor, Source } from "./types";

// Rounded town-center coordinates. minutes are planning estimates from downtown
// St. Louis, not live traffic or a measure of the full corridor's length.
const rows: [string, string, string, number, number, number][] = [
  ["stl", "St. Louis", "MO", 38.627, -90.199, 0],
  ["pacific", "Pacific", "MO", 38.482, -90.741, 45],
  ["union", "Union", "MO", 38.45, -91.008, 60],
  ["washington", "Washington", "MO", 38.558, -91.013, 60],
  ["sullivan", "Sullivan", "MO", 38.209, -91.161, 70],
  ["st-james", "St. James", "MO", 38.001, -91.616, 90],
  ["rolla", "Rolla", "MO", 37.951, -91.771, 101],
  ["st-robert", "St. Robert", "MO", 37.828, -92.177, 120],
  ["waynesville", "Waynesville", "MO", 37.829, -92.201, 125],
  ["lebanon", "Lebanon", "MO", 37.681, -92.664, 160],
  ["marshfield", "Marshfield", "MO", 37.339, -92.907, 180],
  ["springfield-mo", "Springfield", "MO", 37.209, -93.292, 200],
  ["republic", "Republic", "MO", 37.12, -93.48, 220],
  ["nixa", "Nixa", "MO", 37.043, -93.294, 220],
  ["ozark", "Ozark", "MO", 37.021, -93.207, 220],
  ["branson", "Branson", "MO", 36.644, -93.218, 250],
  ["mount-vernon-mo", "Mount Vernon", "MO", 37.103, -93.818, 245],
  ["carthage", "Carthage", "MO", 37.177, -94.31, 245],
  ["webb-city", "Webb City", "MO", 37.146, -94.464, 255],
  ["joplin", "Joplin", "MO", 37.084, -94.513, 260],
  ["neosho", "Neosho", "MO", 36.869, -94.368, 280],
  ["pittsburg", "Pittsburg", "KS", 37.411, -94.705, 290],
  ["warrenton", "Warrenton", "MO", 38.811, -91.141, 60],
  ["kingdom-city", "Kingdom City", "MO", 38.953, -91.942, 95],
  ["fulton", "Fulton", "MO", 38.847, -91.949, 105],
  ["columbia", "Columbia", "MO", 38.952, -92.334, 115],
  ["ashland", "Ashland", "MO", 38.774, -92.259, 125],
  ["jefferson-city", "Jefferson City", "MO", 38.577, -92.174, 123],
  ["holts-summit", "Holts Summit", "MO", 38.64, -92.123, 130],
  ["sedalia", "Sedalia", "MO", 38.705, -93.229, 185],
  ["warrensburg", "Warrensburg", "MO", 38.763, -93.736, 205],
  ["lees-summit", "Lee’s Summit", "MO", 38.911, -94.383, 215],
  ["blue-springs", "Blue Springs", "MO", 39.016, -94.281, 215],
  ["independence", "Independence", "MO", 39.092, -94.416, 220],
  ["raytown", "Raytown", "MO", 39.009, -94.464, 225],
  ["kc-mo", "Kansas City", "MO", 39.1, -94.578, 220],
  ["kc-ks", "Kansas City", "KS", 39.115, -94.627, 230],
  ["gladstone", "Gladstone", "MO", 39.203, -94.554, 240],
  ["liberty", "Liberty", "MO", 39.246, -94.419, 230],
  ["overland-park", "Overland Park", "KS", 38.983, -94.671, 240],
  ["shawnee", "Shawnee", "KS", 39.041, -94.72, 240],
  ["lenexa", "Lenexa", "KS", 38.953, -94.734, 245],
  ["olathe", "Olathe", "KS", 38.881, -94.819, 250],
  ["lawrence", "Lawrence", "KS", 38.972, -95.235, 256],
  ["topeka", "Topeka", "KS", 39.048, -95.678, 275],
  ["troy", "Troy", "MO", 38.98, -90.98, 70],
  ["bowling-green", "Bowling Green", "MO", 39.341, -91.195, 95],
  ["hannibal", "Hannibal", "MO", 39.708, -91.358, 113],
  ["palmyra", "Palmyra", "MO", 39.794, -91.524, 130],
  ["quincy", "Quincy", "IL", 39.936, -91.409, 137],
  ["pittsfield", "Pittsfield", "IL", 39.608, -90.805, 125],
  ["mexico", "Mexico", "MO", 39.17, -91.882, 120],
  ["moberly", "Moberly", "MO", 39.419, -92.438, 150],
  ["macon", "Macon", "MO", 39.742, -92.472, 170],
  ["kirksville", "Kirksville", "MO", 40.195, -92.583, 198],
  ["brookfield", "Brookfield", "MO", 39.785, -93.074, 190],
  ["chillicothe", "Chillicothe", "MO", 39.795, -93.553, 215],
  ["festus", "Festus", "MO", 38.22, -90.396, 40],
  ["farmington", "Farmington", "MO", 37.781, -90.422, 80],
  ["ste-genevieve", "Ste. Genevieve", "MO", 37.982, -90.042, 70],
  ["perryville", "Perryville", "MO", 37.725, -89.862, 90],
  ["jackson", "Jackson", "MO", 37.382, -89.667, 105],
  ["cape", "Cape Girardeau", "MO", 37.305, -89.518, 111],
  ["scott-city", "Scott City", "MO", 37.217, -89.525, 125],
  ["sikeston", "Sikeston", "MO", 36.877, -89.588, 140],
  ["charleston-mo", "Charleston", "MO", 36.92, -89.35, 145],
  ["new-madrid", "New Madrid", "MO", 36.586, -89.528, 165],
  ["hayti", "Hayti", "MO", 36.233, -89.749, 190],
  ["kennett", "Kennett", "MO", 36.236, -90.056, 205],
  ["blytheville", "Blytheville", "AR", 35.927, -89.919, 215],
  ["memphis", "Memphis", "TN", 35.149, -90.049, 248],
  ["belleville", "Belleville", "IL", 38.521, -89.984, 30],
  ["ofallon-il", "O’Fallon", "IL", 38.592, -89.911, 30],
  ["centralia", "Centralia", "IL", 38.526, -89.133, 80],
  ["mount-vernon-il", "Mount Vernon", "IL", 38.317, -88.903, 80],
  ["marion", "Marion", "IL", 37.731, -88.934, 115],
  ["herrin", "Herrin", "IL", 37.803, -89.028, 110],
  ["carbondale", "Carbondale", "IL", 37.727, -89.217, 111],
  ["litchfield", "Litchfield", "IL", 39.176, -89.654, 65],
  ["springfield-il", "Springfield", "IL", 39.782, -89.65, 95],
  ["lincoln", "Lincoln", "IL", 40.148, -89.365, 120],
  ["bloomington-il", "Bloomington", "IL", 40.484, -88.994, 146],
  ["normal", "Normal", "IL", 40.514, -88.99, 150],
  ["peoria", "Peoria", "IL", 40.693, -89.589, 148],
  ["decatur", "Decatur", "IL", 39.84, -88.954, 122],
  ["vandalia", "Vandalia", "IL", 38.96, -89.093, 75],
  ["effingham", "Effingham", "IL", 39.12, -88.543, 100],
  ["mattoon", "Mattoon", "IL", 39.484, -88.377, 130],
  ["charleston-il", "Charleston", "IL", 39.496, -88.176, 140],
  ["champaign", "Champaign", "IL", 40.116, -88.244, 163],
  ["urbana", "Urbana", "IL", 40.11, -88.208, 170],
  ["terre-haute", "Terre Haute", "IN", 39.467, -87.414, 157],
  ["plainfield", "Plainfield", "IN", 39.704, -86.4, 205],
  ["indianapolis", "Indianapolis", "IN", 39.768, -86.158, 221],
  ["speedway", "Speedway", "IN", 39.803, -86.268, 220],
  ["carmel", "Carmel", "IN", 39.978, -86.118, 245],
  ["fishers", "Fishers", "IN", 39.956, -86.014, 245],
  ["greenwood", "Greenwood", "IN", 39.614, -86.106, 225],
  ["martinsville", "Martinsville", "IN", 39.428, -86.429, 215],
  ["bloomington-in", "Bloomington", "IN", 39.165, -86.526, 226],
  ["evansville", "Evansville", "IN", 37.971, -87.571, 158],
  ["henderson", "Henderson", "KY", 37.836, -87.59, 175],
  ["owensboro", "Owensboro", "KY", 37.774, -87.113, 205],
  ["jasper", "Jasper", "IN", 38.391, -86.931, 195],
  ["ferdinand", "Ferdinand", "IN", 38.223, -86.862, 185],
  ["corydon", "Corydon", "IN", 38.212, -86.122, 215],
  ["new-albany", "New Albany", "IN", 38.286, -85.825, 225],
  ["jeffersonville", "Jeffersonville", "IN", 38.277, -85.737, 230],
  ["louisville", "Louisville", "KY", 38.253, -85.759, 229],
];
export const cities: City[] = rows.map(
  ([id, name, state, lat, lng, minutes]) => ({
    id,
    name,
    state,
    lat,
    lng,
    minutes,
  }),
);
export const cityById = Object.fromEntries(
  cities.map((c) => [c.id, c]),
) as Record<string, City>;
export const corridors: Corridor[] = [
  {
    id: 1,
    name: "I-44 technical corridor",
    direction: "Southwest",
    anchor: "rolla",
    minutes: 101,
    format: "Day trip",
    cities: [
      "pacific",
      "washington",
      "union",
      "sullivan",
      "st-james",
      "rolla",
      "st-robert",
      "waynesville",
      "lebanon",
    ],
    summary: "Technical books. Smaller-town sources.",
    reasons: [
      {
        title: "Missouri S&T inventory",
        body: "Look for engineering, science and professional nonfiction around Rolla.",
      },
      {
        title: "Military-family collections",
        body: "St. Robert and Waynesville add moving sales and household collections.",
      },
      {
        title: "Repeatable day route",
        body: "Combine library events with confirmed thrift and estate stops.",
      },
    ],
    targets: [
      "Science & engineering",
      "Professional nonfiction",
      "Homeschool",
      "Library sales",
    ],
    hypothesis: "Low to medium",
    strategy:
      "Anchor on Rolla. Add Lebanon only when confirmed sources justify the extension.",
  },
  {
    id: 2,
    name: "Springfield & Ozarks",
    direction: "Southwest",
    anchor: "springfield-mo",
    minutes: 200,
    format: "Long day",
    cities: [
      "lebanon",
      "marshfield",
      "springfield-mo",
      "republic",
      "nixa",
      "ozark",
      "branson",
    ],
    summary: "Major sales. A wide suburban book pool.",
    reasons: [
      {
        title: "Large Friends sales",
        body: "Spring and fall events are the strongest potential volume anchors.",
      },
      {
        title: "Suburban sources",
        body: "Republic, Nixa and Ozark add independent thrift and estate markets.",
      },
      {
        title: "College households",
        body: "Search general nonfiction, religion, teaching and college collections.",
      },
    ],
    targets: [
      "Large Friends sales",
      "Religious nonfiction",
      "Homeschool",
      "Estates",
    ],
    hypothesis: "Medium; high at major sales",
    strategy:
      "Start at the confirmed sale. Treat Branson as an optional extension, not a default stop.",
  },
  {
    id: 3,
    name: "Joplin & southwest Missouri",
    direction: "Southwest",
    anchor: "joplin",
    minutes: 260,
    format: "Overnight",
    cities: [
      "mount-vernon-mo",
      "carthage",
      "webb-city",
      "joplin",
      "neosho",
      "pittsburg",
    ],
    summary: "Regional towns. An overnight experiment.",
    reasons: [
      {
        title: "Independent small markets",
        body: "Carthage and Webb City widen the search beyond central Joplin.",
      },
      {
        title: "Regional household stock",
        body: "Pair charity stores with churches, estates and school contacts.",
      },
      {
        title: "Test the distance",
        body: "Measure actual contribution per total trip hour before making this repeatable.",
      },
    ],
    targets: [
      "Estates",
      "Charity stores",
      "Church collections",
      "School surplus",
    ],
    hypothesis: "Medium",
    strategy:
      "Leave with several confirmed stops. Long travel requires strong inventory, not extra stops alone.",
  },
  {
    id: 4,
    name: "Central Missouri",
    direction: "West",
    anchor: "columbia",
    minutes: 115,
    format: "Day trip",
    cities: [
      "warrenton",
      "kingdom-city",
      "fulton",
      "columbia",
      "ashland",
      "jefferson-city",
      "holts-summit",
    ],
    summary: "University towns. Repeatable sources.",
    reasons: [
      {
        title: "Columbia library sales",
        body: "Recurring lobby and weekend sales create a repeatable inventory calendar.",
      },
      {
        title: "University inventory",
        body: "Explore education, business and specialized nonfiction in Columbia and Fulton.",
      },
      {
        title: "Short travel overhead",
        body: "Use this close corridor as the benchmark for longer sourcing trips.",
      },
    ],
    targets: [
      "University nonfiction",
      "Business & education",
      "Library sales",
      "Professional books",
    ],
    hypothesis: "Medium",
    strategy:
      "Benchmark this route first. A farther trip should outperform it after travel costs.",
  },
  {
    id: 5,
    name: "Kansas City eastern approach",
    direction: "West",
    anchor: "kc-mo",
    minutes: 220,
    format: "Overnight",
    cities: [
      "sedalia",
      "warrensburg",
      "lees-summit",
      "blue-springs",
      "independence",
      "raytown",
      "kc-mo",
      "kc-ks",
      "gladstone",
      "liberty",
    ],
    summary: "Suburban density. Selective buying.",
    reasons: [
      {
        title: "Enter through smaller markets",
        body: "Use Sedalia and Warrensburg when sources are confirmed.",
      },
      {
        title: "Diverse metro sources",
        body: "Suburbs add stores, libraries, estates and relationship leads.",
      },
      {
        title: "Watch acquisition quality",
        body: "Compare contribution per sourcing hour, not vehicle fullness.",
      },
    ],
    targets: [
      "Suburban thrift",
      "Estates",
      "Library events",
      "Professional nonfiction",
    ],
    hypothesis: "High",
    strategy:
      "Pick a metro cluster before leaving. Avoid spending the day crossing the whole city.",
  },
  {
    id: 6,
    name: "Johnson County, Lawrence & Topeka",
    direction: "West",
    anchor: "topeka",
    minutes: 275,
    format: "Overnight",
    cities: [
      "overland-park",
      "shawnee",
      "lenexa",
      "olathe",
      "lawrence",
      "topeka",
    ],
    summary: "Weekly book stock. University inventory.",
    reasons: [
      {
        title: "Lenexa Book Nook",
        body: "A recurring weekend bookstore provides a repeatable anchor.",
      },
      {
        title: "Lawrence university market",
        body: "KU adds academic and professional household collections.",
      },
      {
        title: "Topeka sale calendar",
        body: "Build the second day around a confirmed major sale.",
      },
    ],
    targets: [
      "Permanent Friends stores",
      "University nonfiction",
      "Bag sales",
      "Estates",
    ],
    hypothesis: "High",
    strategy:
      "Combine Johnson County on day one with Lawrence or Topeka on day two.",
  },
  {
    id: 7,
    name: "Hannibal & Quincy",
    direction: "North",
    anchor: "quincy",
    minutes: 137,
    format: "Day trip",
    cities: [
      "troy",
      "bowling-green",
      "hannibal",
      "palmyra",
      "quincy",
      "pittsfield",
    ],
    summary: "Older collections. A manageable day out.",
    reasons: [
      {
        title: "Quincy Friends events",
        body: "Use the sale calendar as an anchor before adding other stops.",
      },
      {
        title: "Household collections",
        body: "Search history, religion, agriculture and education from local estates.",
      },
      {
        title: "Close enough to repeat",
        body: "A full day still leaves a manageable drive home.",
      },
    ],
    targets: ["History", "Agriculture", "Religious books", "Estates"],
    hypothesis: "Low to medium",
    strategy:
      "Start with a Quincy or Hannibal event. Pittsfield is an optional return branch.",
  },
  {
    id: 8,
    name: "North central Missouri",
    direction: "Northwest",
    anchor: "kirksville",
    minutes: 198,
    format: "Long day",
    cities: [
      "mexico",
      "moberly",
      "macon",
      "kirksville",
      "brookfield",
      "chillicothe",
    ],
    summary: "Rural relationships. Confirm before departure.",
    reasons: [
      {
        title: "Kirksville campuses",
        body: "Truman State and A.T. Still add academic households.",
      },
      {
        title: "Relationship sourcing",
        body: "Ask schools, churches and estate companies about future collections.",
      },
      {
        title: "Low-density test",
        body: "Measure stop yield. Do not assume less visible competition means more profit.",
      },
    ],
    targets: [
      "Direct pickups",
      "School surplus",
      "University moves",
      "Estates",
    ],
    hypothesis: "Low",
    strategy:
      "Require appointments or several confirmed events. Brookfield and Chillicothe are branches.",
  },
  {
    id: 9,
    name: "Southeast Missouri",
    direction: "Southeast",
    anchor: "cape",
    minutes: 111,
    format: "Day trip",
    cities: [
      "festus",
      "farmington",
      "ste-genevieve",
      "perryville",
      "jackson",
      "cape",
      "scott-city",
      "sikeston",
    ],
    summary: "College stock. Small-town estates.",
    reasons: [
      {
        title: "Cape university market",
        body: "SEMO adds student and professional collections.",
      },
      {
        title: "Smaller surrounding markets",
        body: "Perryville, Jackson and Ste. Genevieve add independent sources.",
      },
      {
        title: "Simple day corridor",
        body: "Sikeston is the extension when confirmed stops justify it.",
      },
    ],
    targets: [
      "College nonfiction",
      "Church sales",
      "Estates",
      "Library events",
    ],
    hypothesis: "Low to medium",
    strategy:
      "Focus the day around Cape. Farmington is a branch, not an automatic through-stop.",
  },
  {
    id: 10,
    name: "I-55 to Memphis",
    direction: "South",
    anchor: "memphis",
    minutes: 248,
    format: "Overnight",
    cities: [
      "scott-city",
      "sikeston",
      "charleston-mo",
      "new-madrid",
      "hayti",
      "kennett",
      "blytheville",
      "memphis",
    ],
    summary: "A southern expedition with confirmed anchors.",
    reasons: [
      {
        title: "Memphis source diversity",
        body: "Pair Friends inventory with estate and charity-store leads.",
      },
      {
        title: "Collect along I-55",
        body: "Confirmed stops along the highway should support the expedition.",
      },
      {
        title: "Charge the full trip",
        body: "Include the hotel and all highway hours in the comparison.",
      },
    ],
    targets: [
      "Friends bookstores",
      "Regional estates",
      "Church collections",
      "Thrift stores",
    ],
    hypothesis: "Low outside Memphis; medium-high in metro",
    strategy:
      "Use Memphis as the anchor. Avoid an eight-hour round trip for one unconfirmed shop.",
  },
  {
    id: 11,
    name: "Southern Illinois",
    direction: "Southeast",
    anchor: "carbondale",
    minutes: 111,
    format: "Day trip",
    cities: [
      "belleville",
      "ofallon-il",
      "centralia",
      "mount-vernon-il",
      "marion",
      "herrin",
      "carbondale",
    ],
    summary: "SIU territory. Independent source channels.",
    reasons: [
      {
        title: "SIU household inventory",
        body: "Carbondale adds an academic inventory pool.",
      },
      {
        title: "Regional source mix",
        body: "Marion, Herrin and Mount Vernon add estate and thrift opportunities.",
      },
      {
        title: "Check scanner rules",
        body: "The supplied research reports restrictions at a Carbondale Friends sale. Confirm each event.",
      },
    ],
    targets: [
      "University collections",
      "Estates",
      "Church sales",
      "Thrift stores",
    ],
    hypothesis: "Low to medium",
    strategy:
      "Verify scanning rules before traveling. Build around sources permitting your buying workflow.",
  },
  {
    id: 12,
    name: "Central Illinois loop",
    direction: "Northeast",
    anchor: "peoria",
    minutes: 148,
    format: "Day trip",
    cities: [
      "litchfield",
      "springfield-il",
      "lincoln",
      "bloomington-il",
      "normal",
      "peoria",
      "decatur",
    ],
    summary: "Independent markets. One flexible loop.",
    reasons: [
      {
        title: "College and government households",
        body: "Normal and Springfield add education and professional collections.",
      },
      {
        title: "Peoria regional market",
        body: "Use Friends inventory and confirmed local events as anchors.",
      },
      {
        title: "Flexible return through Decatur",
        body: "Choose a smaller loop rather than trying every town in one day.",
      },
    ],
    targets: [
      "Education",
      "Government & business",
      "Friends inventory",
      "Estates",
    ],
    hypothesis: "Medium",
    strategy:
      "Select two or three market clusters. A full seven-town sourcing day needs realistic stop times.",
  },
  {
    id: 13,
    name: "Champaign & eastern Illinois",
    direction: "East",
    anchor: "champaign",
    minutes: 163,
    format: "Long day",
    cities: [
      "vandalia",
      "effingham",
      "mattoon",
      "charleston-il",
      "champaign",
      "urbana",
      "terre-haute",
    ],
    summary: "Academic inventory. Regular bookstore stock.",
    reasons: [
      {
        title: "Champaign FriendShop",
        body: "A permanent bookstore and monthly discounts create recurring opportunities.",
      },
      {
        title: "University households",
        body: "UIUC and Eastern Illinois add specialized nonfiction.",
      },
      {
        title: "Terre Haute branch",
        body: "Indiana State and Rose-Hulman add a separate academic market.",
      },
    ],
    targets: [
      "Academic nonfiction",
      "FriendShop",
      "Professional books",
      "Moving sales",
    ],
    hypothesis: "Medium to high",
    strategy:
      "Choose Champaign or Terre Haute as the day's anchor. Both branches add substantial driving.",
  },
  {
    id: 14,
    name: "Indianapolis & Bloomington",
    direction: "East",
    anchor: "indianapolis",
    minutes: 221,
    format: "Overnight",
    cities: [
      "terre-haute",
      "plainfield",
      "indianapolis",
      "speedway",
      "carmel",
      "fishers",
      "greenwood",
      "martinsville",
      "bloomington-in",
    ],
    summary: "Major sale cycles. Two distinct clusters.",
    reasons: [
      {
        title: "Indy Library Store cycles",
        body: "Regular sale, half-price and bag days provide multiple buying strategies.",
      },
      {
        title: "Focused metro clusters",
        body: "Choose the western/southern cluster or the northern suburbs.",
      },
      {
        title: "Bloomington university market",
        body: "IU adds an optional second-day academic anchor.",
      },
    ],
    targets: [
      "Large library sales",
      "Academic nonfiction",
      "Suburban thrift",
      "Estates",
    ],
    hypothesis: "High",
    strategy:
      "Plan an overnight and one metro cluster. Confirm local event times in Eastern Time.",
  },
  {
    id: 15,
    name: "Evansville & Louisville",
    direction: "East / southeast",
    anchor: "louisville",
    minutes: 229,
    format: "Overnight",
    cities: [
      "mount-vernon-il",
      "evansville",
      "henderson",
      "owensboro",
      "jasper",
      "ferdinand",
      "corydon",
      "new-albany",
      "jeffersonville",
      "louisville",
    ],
    summary: "Southern Indiana. Two regional anchors.",
    reasons: [
      {
        title: "Evansville as a day route",
        body: "A confirmed sale supports a shorter standalone trip.",
      },
      {
        title: "Louisville branch network",
        body: "Search neighborhood Friends groups and suburban sources.",
      },
      {
        title: "Manage the branches",
        body: "Owensboro and Jasper are alternatives, not mandatory detours.",
      },
    ],
    targets: [
      "Friends sales",
      "Neighborhood sources",
      "Estates",
      "Professional nonfiction",
    ],
    hypothesis: "Medium to high",
    strategy:
      "Use Evansville alone for a long day, or connect to Louisville with an overnight.",
  },
];
export const routeById = Object.fromEntries(
  corridors.map((r) => [r.id, r]),
) as Record<number, Corridor>;
export const sourceTypes = [
  "Goodwill outlet",
  "Friends bookstore",
  "Library sale",
  "Thrift store",
  "Estate sale",
  "Church sale",
  "School / university",
  "Direct pickup",
  "Other",
];
export const seedSources: Source[] = [
  {
    id: "seed-columbia",
    routeId: 4,
    cityId: "columbia",
    name: "Columbia Public Library Friends",
    type: "Library sale",
    address: "100 W. Broadway, Columbia, MO",
    hours: "Lobby sales Wednesday & Saturday, noon–3 pm CT",
    pricing: "Varies by sale. Cash or checks for lobby sales.",
    contact: "573-443-3161",
    url: "https://www.dbrl.org/friends",
    scanPolicy: "Unknown",
    notes:
      "Four large weekend sales each year, themed monthly sales and regular lobby sales. Check the library calendar before departure.",
    verifiedAt: "2026-10-01",
    nextDate: "",
    endDate: "",
  },
  {
    id: "seed-quincy",
    routeId: 7,
    cityId: "quincy",
    name: "Quincy Friends fall book sale",
    type: "Library sale",
    address: "526 Jersey St., Quincy, IL 62301",
    hours: "Oct 8: 9:30 am–7:30 pm. Oct 9–10: 9:30 am–4:30 pm CT",
    pricing: "$0.50 per inch. Specialty items separately priced.",
    contact: "217-223-1309",
    url: "https://www.quincylibrary.org/events/list?bundles%5Blc_event%5D=lc_event&page=1",
    scanPolicy: "Unknown",
    notes:
      "Annual Friends fall sale in the Large Meeting Room. Confirm the event and scanner rules before traveling.",
    verifiedAt: "2026-10-01",
    nextDate: "2026-10-08",
    endDate: "2026-10-10",
  },
  {
    id: "seed-lenexa",
    routeId: 6,
    cityId: "lenexa",
    name: "Friends Book Nook",
    type: "Friends bookstore",
    address: "8281 Melrose Drive, Lenexa, KS 66214",
    hours: "Saturday & Sunday, 10 am–3 pm CT",
    pricing: "Prices start at $0.25. Friends members receive 20% off.",
    contact: "913-492-4791",
    url: "https://friendsofjcl.org/",
    scanPolicy: "Unknown",
    notes:
      "More than 16,000 items listed, with new stock shelved weekly. Confirm holiday and weather closures.",
    verifiedAt: "2026-10-01",
    nextDate: "",
    endDate: "",
  },
  {
    id: "seed-topeka",
    routeId: 6,
    cityId: "topeka",
    name: "Topeka Friends book & media sale",
    type: "Library sale",
    address: "1515 SW 10th Ave., Topeka, KS 66604",
    hours:
      "Oct 16 members: 5–8 pm. Oct 17 public: 9 am–3 pm. Oct 18 bags: noon–3 pm CT",
    pricing: "Most hardbacks and paperbacks $2. Sunday $10 bag sale.",
    contact: "",
    url: "https://tscpl.org/friends-of-the-library/book-media-sales",
    scanPolicy: "Unknown",
    notes:
      "Sale in Marvin Auditorium. Friday access requires membership. Public Saturday and Sunday admission is free.",
    verifiedAt: "2026-10-01",
    nextDate: "2026-10-16",
    endDate: "2026-10-18",
  },
  {
    id: "seed-champaign",
    routeId: 13,
    cityId: "champaign",
    name: "FriendShop Bookstore",
    type: "Friends bookstore",
    address: "200 W. Green St., Champaign, IL 61820",
    hours: "Wednesday–Sunday, 1–4 pm CT",
    pricing:
      "Most items $2 or less. Member half-price week. $1 tag bags last week of month.",
    contact: "217-403-5395",
    url: "https://champaign.org/friendshop",
    scanPolicy: "Unknown",
    notes:
      "More than 20,000 books and media items listed. Check the monthly calendar for exact discount dates.",
    verifiedAt: "2026-10-01",
    nextDate: "",
    endDate: "",
  },
  {
    id: "seed-indy",
    routeId: 14,
    cityId: "indianapolis",
    name: "Indy Library Store October sale",
    type: "Library sale",
    address: "2450 N. Meridian St., Indianapolis, IN 46208",
    hours: "Oct 9 members: 4–7 pm. Oct 10: 10 am–5 pm. Oct 12–13: noon–7 pm ET",
    pricing:
      "Adult hardbacks $3, softbacks $1. Oct 12 half price. Oct 13 $10 bags.",
    contact: "",
    url: "https://indyplfoundation.org/book-sale",
    scanPolicy: "Unknown",
    notes:
      "Friday is Friends Night. Public Saturday, half-price Monday and bag Tuesday. Indianapolis is one hour ahead of St. Louis in October.",
    verifiedAt: "2026-10-01",
    nextDate: "2026-10-09",
    endDate: "2026-10-13",
  },
];
