import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
import { createClient } from '@supabase/supabase-js';
import pg from 'pg';
import { newTrip,newCityVisit } from '../src/lib/planning/draft';
const fixture=JSON.parse(await readFile('private/qa-users.json','utf8'));
if(!fixture.url.startsWith('http://127.0.0.1:57321'))throw new Error('This test may only target the synthetic local QA stack.');
const tokenFor=async(label:string)=>{const user=fixture.users.find((x:{label:string})=>x.label===label),client=createClient(fixture.url,fixture.key,{auth:{persistSession:false}}),result=await client.auth.signInWithPassword({email:user.email,password:user.password});assert.ifError(result.error);return result.data.session!.access_token;};
const owner=await tokenFor('owner'),outsider=await tokenFor('outsider'),partner=await tokenFor('partner');
const outsideClient=createClient(fixture.url,fixture.key,{global:{headers:{Authorization:'Bearer '+outsider}},auth:{persistSession:false}});for(const table of ['workspaces','workspace_members','workspace_settings','cities','corridors','corridor_cities','sources','source_events','food_places','vehicles','trips','trip_days','city_visits','trip_stops','trip_participants','trip_vehicle_assignments','trip_driver_assignments','lodging_stays','source_visits','notes','trip_expenses','evidence_records','import_runs','legacy_records','legacy_snapshots']){const q=outsideClient.from(table).select('*');const denied=await (table==='workspaces'?q.eq('id',fixture.workspaceId):q.eq('workspace_id',fixture.workspaceId));assert.ifError(denied.error);assert.deepEqual(denied.data,[],table+' outsider rows');}
const call=async(path:string,token:string,body?:unknown,origin='http://127.0.0.1:3000')=>fetch('http://127.0.0.1:3000/api/workspaces/'+fixture.workspaceId+'/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
const origin={id:'synthetic-qa-base',label:'Synthetic QA base (not a real address)',address:'Synthetic test access',lat:38.5,lng:-91,zone:'America/Chicago',precision:'exact',confirmed:true};assert.equal((await call('settings',owner,origin)).status,200);assert.equal((await call('settings',partner,origin)).status,403);assert.equal((await call('settings',outsider,origin)).status,403);
assert.equal((await call('data',owner)).status,200);assert.equal((await call('data',outsider)).status,403);assert.equal((await call('data','invalid-token')).status,401);
const mutation=randomUUID(),visit={city_id:fixture.cityId,source_id:null,trip_id:null,visited_at:'2026-10-01T15:00:00Z',bought:0,scanned:2,usable:0,purchase_cents:0,minutes:20,notes:'Synthetic empty sourcing result, not legacy data.',mutation_key:mutation};
const first=await call('visits',owner,visit),firstBody=await first.json();assert.equal(first.status,200);const retry=await call('visits',owner,visit);assert.equal((await retry.json()).visit.id,firstBody.visit.id);assert.equal((await call('visits',outsider,{...visit,mutation_key:randomUUID()})).status,403);assert.equal((await call('visits',partner,visit)).status,409);
assert.equal((await call('notes',owner,{city_id:fixture.cityId,body:'Cross origin must fail',mutation_key:randomUUID()},'https://wrong-origin.invalid')).status,403);
const trip=newTrip([fixture.users.find((x:{label:string})=>x.label==='owner').id],'2026-10-05');trip.days[0].visits=[newCityVisit({id:fixture.cityId,name:'Synthetic QA city',state:'XX',zone:'America/Chicago',lat:38.5,lng:-91,overview:'',provenance:'test fixture',corridor:''})];
const saves=await Promise.all([call('trips',owner,trip),call('trips',owner,trip)]);assert.deepEqual(saves.map(s=>s.status).sort(),[200,409]);assert.equal((await call('trips',outsider,trip)).status,403);
const route=await call('routes',owner,trip),routeBody=await route.json();assert.equal(route.status,200);assert.equal(routeBody.status,'unavailable');assert.deepEqual(routeBody.legs,[]);assert.equal((await call('routes',outsider,trip)).status,403);
// Direct real Postgres concurrency, bypassing only HTTP; member authorization remains active.
const env=await readFile('private/qa-db.env','utf8'),password=env.trim().slice('POSTGRES_PASSWORD='.length),connection='postgres://postgres:'+password+'@127.0.0.1:57322/postgres';
const clients=[new pg.Client({connectionString:connection}),new pg.Client({connectionString:connection})];try{for(const c of clients){await c.connect();await c.query("select set_config('request.jwt.claim.sub',$1,false)",[trip.participants[0]]);await c.query('set role authenticated');}
 const fresh={...trip,id:randomUUID(),days:trip.days.map(d=>({...d,id:randomUUID(),visits:d.visits.map(v=>({...v,id:randomUUID()}))}))};const results=await Promise.allSettled(clients.map(c=>c.query('select public.save_trip($1,$2,0,$3::jsonb)',[fixture.workspaceId,fresh.id,JSON.stringify(fresh)])));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);
 }finally{for(const c of clients)await c.end();}
console.log('PASS: real authenticated API saves/retry; zero-book results; outsider and forged-token denial; creator ownership; same-origin protection; concurrent API and Postgres save conflicts; honest routing failure.');
