"use client";
import { Plus, Trash2 } from "lucide-react";
import type { City, TripDay, CityVisit, Source, SourceEvent } from "@/lib/model";
import { newStop, newCityVisit } from "@/lib/planning/draft";
import { PointFields, NumberField } from "@/components/ui/Fields";
import StopEditor from "./StopEditor";
import WindowFields from '@/components/ui/WindowFields';
export default function DayEditor({ day, dayIndex, isLast, cities, sources, events, onChange }: { day: TripDay; dayIndex: number; isLast: boolean; cities: City[]; sources: Source[]; events: SourceEvent[]; onChange: (d: TripDay) => void }) {
  const updateVisit = (id: string, next: CityVisit) => onChange({ ...day, visits: day.visits.map(v => v.id===id ? next : v) });
  return <section className="day-editor">
    <div className="section-heading"><h2>Day {dayIndex + 1}</h2><label>Date<input type="date" value={day.date} onChange={e => onChange({ ...day,date:e.target.value })} /></label></div>
    <div className="field-pair"><label>Departure local time<input type="time" value={day.departureLocal} onChange={e => onChange({ ...day,departureLocal:e.target.value })} /></label><label>{isLast ? "Day target" : "Hotel arrival target"}<input type="time" value={day.deadlineLocal} onChange={e => onChange({ ...day,deadlineLocal:e.target.value })} /></label></div>
    {day.visits.map(visit => <section className="city-visit-editor" key={visit.id}>
      <div className="section-heading"><h3>{visit.cityName}</h3><button className="icon-button" aria-label={"Remove city " + visit.cityName} onClick={() => onChange({ ...day,mealAfterVisitId:day.mealAfterVisitId===visit.id?null:day.mealAfterVisitId,visits:day.visits.filter(v => v.id!==visit.id) })}><Trash2 size={18} /></button></div>
      <p className="secondary">{visit.zone} · {visit.stops.length} store/event stops</p>
      <NumberField label="Shared city sourcing window (hours)" min={1} max={10} step={0.5} value={visit.reservedMinutes/60} onChange={v => updateVisit(visit.id,{ ...visit,reservedMinutes:Math.round((v ?? 4)*60) })} />
      <p className="secondary">Across all stores, local transfers and ordinary parking/loading. Detailed stops consume this window once.</p>
      <label>Add a catalog source / dated event<select value="" onChange={e=>{const [kind,id]=e.target.value.split(':');const event=kind==='event'?events.find(x=>x.id===id):null;const source=sources.find(x=>x.id===(event?.source_id||id));if(source)updateVisit(visit.id,{...visit,stops:[...visit.stops,{...newStop(),sourceId:source.id,eventId:event?.id||null,kind:event?'event':'store',name:event?.name||source.name,category:source.category,point:source.point,windows:event?.windows||source.windows,evidenceUrl:event?.evidence_url||source.evidence_url,checkedAt:event?.checked_at||source.checked_at}]});}}><option value="">Choose an actual source or event</option>{sources.filter(s=>s.city_id===visit.cityId && s.category!=='regular_goodwill' && s.category!=='half_price_books').map(s=><option key={s.id} value={'source:'+s.id}>{s.name}{s.is_lead?' · unconfirmed lead':''}</option>)}{events.filter(e=>sources.some(s=>s.id===e.source_id&&s.city_id===visit.cityId)).map(e=><option key={e.id} value={'event:'+e.id}>{e.name} · dated event</option>)}</select></label>
      {visit.stops.map((stop,i) => <StopEditor key={stop.id} stop={stop} date={day.date} zone={visit.zone} index={i} count={visit.stops.length} onChange={next => updateVisit(visit.id,{ ...visit,stops:visit.stops.map(s => s.id===stop.id ? next : s) })} onRemove={() => updateVisit(visit.id,{ ...visit,stops:visit.stops.filter(s => s.id!==stop.id) })} onMove={direction => { const stops=[...visit.stops]; [stops[i],stops[i+direction]]=[stops[i+direction],stops[i]]; updateVisit(visit.id,{ ...visit,stops }); }} />)}
      <button className="text-button" onClick={() => updateVisit(visit.id,{ ...visit,stops:[...visit.stops,newStop()] })}><Plus size={17} />Add store or event</button>
    </section>)}
    <label>Add a sourcing city<select value="" onChange={e => { const c=cities.find(c => c.id===e.target.value); if(c) onChange({ ...day,visits:[...day.visits,newCityVisit(c)] }); }}><option value="">Choose a city</option>{cities.map(c => <option key={c.id} value={c.id}>{c.name}, {c.state}</option>)}</select></label>
    {day.visits.length>1 && <p className="notice">Another city needs its full work window, actual driving and opening hours. Visits will not be compressed.</p>}
    <h3>Meals, setup & loading</h3>
    <div className="field-triple"><NumberField label="Arrival setup minutes" value={day.setupMinutes} onChange={v => onChange({ ...day,setupMinutes:v ?? 0 })} /><NumberField label="Packed meal minutes" value={day.mealMinutes} onChange={v => onChange({ ...day,mealMinutes:v ?? 0 })} /><NumberField label="Extra bulk loading minutes" value={day.extraLoadingMinutes} onChange={v => onChange({ ...day,extraLoadingMinutes:v ?? 0 })} /></div>
    <label>Meal / extra load after<select value={day.mealAfterVisitId || ""} onChange={e => onChange({ ...day,mealAfterVisitId:e.target.value || null })}><option value="">First city</option>{day.visits.map(v => <option key={v.id} value={v.id}>{v.cityName}</option>)}</select></label>
    <details><summary>Off-site meal location (optional)</summary><PointFields point={day.mealPoint} onChange={mealPoint=>onChange({...day,mealPoint})} label="Selected meal stop" zone={day.visits[0]?.zone}/>{day.mealPoint&&<WindowFields label="Meal opening window" window={day.mealWindow} onChange={mealWindow=>onChange({...day,mealWindow})} date={day.date} zone={day.mealPoint.zone}/>}</details>
    <p className="secondary">A packed/on-site meal needs no additional route. An off-site meal uses its exact access point and full transfers. Halal status still requires source evidence.</p>
    <NumberField label="Protected daily activity limit (hours)" min={4} max={16} value={day.maxActiveMinutes/60} onChange={v=>onChange({...day,maxActiveMinutes:Math.round((v??12)*60)})}/>
    {!isLast && <section className="lodging-editor"><h3>Night {dayIndex + 1} · overnight lodging</h3><PointFields point={day.hotel} onChange={hotel => onChange({ ...day,hotel })} label="Selected lodging" zone={day.visits.at(-1)?.zone} /><label className="check-label"><input type="checkbox" checked={day.hotelConfirmed} onChange={e => onChange({ ...day,hotelConfirmed:e.target.checked })} />Lodging and check-in availability verified</label><div className="field-triple"><NumberField label="Check-in minutes" value={day.checkInMinutes} onChange={v => onChange({ ...day,checkInMinutes:v ?? 0 })} /><NumberField label="Check-out minutes" value={day.checkOutMinutes} onChange={v => onChange({ ...day,checkOutMinutes:v ?? 0 })} /><NumberField label="Protected rest (hours)" min={6} max={14} value={day.restMinutes/60} onChange={v => onChange({ ...day,restMinutes:Math.round((v ?? 8)*60) })} /></div><WindowFields label="Confirmed hotel check-in window" window={day.checkInWindow} onChange={checkInWindow=>onChange({...day,checkInWindow})} date={day.date} zone={day.hotel?.zone||day.visits.at(-1)?.zone||"America/Chicago"}/><p className="secondary">This ends today and starts tomorrow at the actual selected location. No hotel is booked.</p></section>}
  </section>;
}
