"use client";
import { Plus, Trash2 } from 'lucide-react';
import type { TripDraft, Vehicle, Member } from '@/lib/model';
import { evaluateEconomics, breakEvenBooks } from '@/lib/planning/economics';
import { PointFields, NumberField } from '@/components/ui/Fields';
import WindowFields from '@/components/ui/WindowFields';
const money=(cents:number|null)=>cents===null?'Unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
export default function ScenarioPanel({trip,vehicles,members,personHours,roadMeters,onChange}:{trip:TripDraft;vehicles:Vehicle[];members:Member[];personHours:number[]|null;roadMeters:number|null;onChange:(t:TripDraft)=>void}){
 const econ=trip.economics,t=trip.transport,result=evaluateEconomics(econ,personHours,roadMeters),a=econ.alternative||{extraCostCents:null,extraUsableBooks:null,extraHoursPerPerson:null,evidence:''};
 const updateTransport=(patch:Partial<typeof t>)=>onChange({...trip,transport:{...t,...patch}});
 const updateEcon=(patch:Partial<typeof econ>)=>onChange({...trip,economics:{...econ,...patch}});
 const extraContribution=a.extraUsableBooks!==null&&econ.contributionPerBookCents!==null&&a.extraCostCents!==null&&a.evidence.trim()?a.extraUsableBooks*econ.contributionPerBookCents-a.extraCostCents:null;
 const altHours=result.totalPersonHours!==null&&a.extraHoursPerPerson!==null?result.totalPersonHours+a.extraHoursPerPerson*trip.participants.length:null;
 return <section className="scenario-panel"><h2>Vehicle & sourcing economics</h2><p>Entered estimates stay projections. Untested cities do not receive an invented yield or rating.</p>
  <label>Vehicle scenario<select value={t.mode} onChange={e=>updateTransport({mode:e.target.value as 'car'|'truck'})}><option value="car">Personal vehicle</option><option value="truck">Rental truck</option></select></label>
  <fieldset><legend>Assigned vehicle resources</legend>{vehicles.length?vehicles.map(v=><label key={v.id} className="check-label"><input type="checkbox" checked={t.vehicleIds.includes(v.id)} onChange={e=>{const ids=e.target.checked?[...t.vehicleIds,v.id]:t.vehicleIds.filter(id=>id!==v.id);updateTransport({vehicleIds:ids,driverAssignments:t.driverAssignments.filter(a=>ids.includes(a.vehicleId)),...(ids.length===1&&e.target.checked?{payloadKg:v.payload_kg,capacityLiters:v.volume_liters}:{})});}}/>{v.name}</label>):<p>Add a real vehicle in Settings. No car or rental is assumed.</p>}</fieldset>
  {vehicles.filter(v=>t.vehicleIds.includes(v.id)).map(v=><label key={v.id}>Assigned driver · {v.name}<select value={t.driverAssignments.find(a=>a.vehicleId===v.id)?.userId||''} onChange={e=>updateTransport({driverAssignments:[...t.driverAssignments.filter(a=>a.vehicleId!==v.id),...(e.target.value?[{vehicleId:v.id,userId:e.target.value}]:[])]})}><option value="">Choose a confirmed eligible driver</option>{members.filter(m=>trip.participants.includes(m.user_id)).map(m=><option key={m.user_id} value={m.user_id}>{m.display_name}</option>)}</select></label>)}
  <NumberField label="Confirmed eligible drivers" max={trip.participants.length} value={t.eligibleDrivers} onChange={v=>updateTransport({eligibleDrivers:v??0})}/>
  <div className="field-pair"><NumberField label="Usable payload kg" value={t.payloadKg} onChange={v=>updateTransport({payloadKg:v})}/><NumberField label="Cargo kg" value={t.cargoKg} onChange={v=>updateTransport({cargoKg:v})}/><NumberField label="People / gear kg" value={t.peopleGearKg} onChange={v=>updateTransport({peopleGearKg:v})}/><NumberField label="Usable cargo liters" value={t.capacityLiters} onChange={v=>updateTransport({capacityLiters:v})}/><NumberField label="Expected cargo liters" value={t.cargoLiters} onChange={v=>updateTransport({cargoLiters:v})}/></div>
  {t.mode==='truck'&&<><p className="notice">Car directions do not certify truck clearances. Verify model-specific restrictions separately. Nothing is booked.</p><label className="check-label"><input type="checkbox" checked={t.roadRestrictionsVerified} onChange={e=>updateTransport({roadRestrictionsVerified:e.target.checked})}/>I checked vehicle-specific road restrictions</label><label className="check-label"><input type="checkbox" checked={t.destinationPickup} onChange={e=>updateTransport({destinationPickup:e.target.checked})}/>Truck pickup at destination</label><label className="check-label"><input type="checkbox" checked={t.carMustReturn} onChange={e=>updateTransport({carMustReturn:e.target.checked})}/>Personal car must also return home</label><label>Car return / transfer plan<textarea value={t.transferPlan} onChange={e=>updateTransport({transferPlan:e.target.value})}/></label><PointFields point={t.pickup} onChange={pickup=>updateTransport({pickup})} label="Rental pickup depot"/><WindowFields label="Rental pickup window" window={t.pickupWindow} onChange={pickupWindow=>updateTransport({pickupWindow})} date={trip.days[0].date} zone={t.pickup?.zone||trip.homeZone}/><PointFields point={t.returnDepot} onChange={returnDepot=>updateTransport({returnDepot})} label="Rental return depot"/><WindowFields label="Rental return window" window={t.returnWindow} onChange={returnWindow=>updateTransport({returnWindow})} date={trip.returnDate} zone={t.returnDepot?.zone||trip.homeZone}/><div className="field-pair"><NumberField label="Pickup / inspection minutes" value={t.pickupMinutes} onChange={v=>updateTransport({pickupMinutes:v??0})}/><NumberField label="Unloading / return minutes" value={t.returnMinutes} onChange={v=>updateTransport({returnMinutes:v??0})}/></div><p className="secondary">Destination pickup remains provisional until the original car’s separate route and costs are validated. A solo driver cannot move two vehicles simultaneously.</p></>}
  <h3>Book contribution assumption</h3><div className="field-pair"><NumberField label="Expected usable books" value={econ.usableBooks} onChange={v=>updateEcon({usableBooks:v})}/><NumberField label="Contribution per usable book ($)" min={-1000} step={0.01} value={econ.contributionPerBookCents===null?null:econ.contributionPerBookCents/100} onChange={v=>updateEcon({contributionPerBookCents:v===null?null:Math.round(v*100)})}/></div><label>Costs already included in book contribution<textarea value={econ.contributionBasis} onChange={e=>updateEcon({contributionBasis:e.target.value})} placeholder="Acquisition, marketplace fees, prep, freight, reserves…"/></label>
  <h3>Incremental trip costs</h3><p className="secondary">Enter confirmed quotes or labeled estimates for rental, miles/fuel, tolls, lodging and transfers. Unknown costs stay unknown. Shared costs are charged once. Per-mile estimates update with the current road route; unknown driving makes those costs unavailable.</p>
  {econ.costs.map((c,i)=>{const update=(patch:Partial<typeof c>)=>updateEcon({costs:econ.costs.map((x,j)=>j===i?{...x,...patch}:x)});return <div key={c.id} className="cost-row"><label>Cost name<input value={c.name} onChange={e=>update({name:e.target.value})}/></label><label>Calculation<select value={c.pricing} onChange={e=>update({pricing:e.target.value as typeof c.pricing})}><option value="fixed">Fixed quote / estimate</option><option value="per_mile">Per routed road mile</option></select></label>{c.pricing==='per_mile'?<NumberField label="Entered cost / road mile ($)" step={0.001} value={c.centsPerMile===null?null:c.centsPerMile/100} onChange={v=>update({centsPerMile:v===null?null:v*100})}/>:<NumberField label="Amount ($)" step={0.01} value={c.cents===null?null:c.cents/100} onChange={v=>update({cents:v===null?null:Math.round(v*100)})}/>}<label>Basis<select value={c.basis} onChange={e=>update({basis:e.target.value as typeof c.basis})}><option value="other">Quoted / entered cost</option><option value="fuel">Fuel</option><option value="mileage_inclusive">Mileage includes fuel</option></select></label><label>Cost vehicle<select value={c.vehicleId||''} onChange={e=>update({vehicleId:e.target.value||null})}><option value="">Shared trip vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><button className="icon-button" aria-label={'Remove cost '+c.name} onClick={()=>updateEcon({costs:econ.costs.filter((_,j)=>j!==i)})}><Trash2 size={18}/></button></div>;})}<button className="text-button" onClick={()=>updateEcon({costs:[...econ.costs,{id:crypto.randomUUID(),name:'Unquoted cost',cents:null,basis:'other',vehicleId:null,pricing:'fixed',centsPerMile:null}]})}><Plus size={16}/>Add trip cost</button>
  {result.errors.map(e=><p className="notice" key={e}>{e}</p>)}<dl className="economic-totals"><div><dt>Projected book contribution</dt><dd>{money(result.bookContributionCents)}</dd></div><div><dt>Shared trip costs</dt><dd>{money(result.tripCostsCents)}</dd></div><div><dt>Contribution before labor</dt><dd>{money(result.contributionCents)}</dd></div><div><dt>Contribution / total person-hour</dt><dd>{money(result.perPersonHourCents)}</dd></div></dl>
  <h3>Does another night / truck earn its cost?</h3><p className="secondary">Evidence-backed incremental comparison. Its yield and itinerary remain estimates; validate the alternative as a separate saved trip.</p><div className="field-triple"><NumberField label="Extra quoted/entered cost ($)" step={0.01} value={a.extraCostCents===null?null:a.extraCostCents/100} onChange={v=>updateEcon({alternative:{...a,extraCostCents:v===null?null:Math.round(v*100)}})}/><NumberField label="Additional usable books" value={a.extraUsableBooks} onChange={v=>updateEcon({alternative:{...a,extraUsableBooks:v}})}/><NumberField label="Extra door-to-door hours / person" value={a.extraHoursPerPerson} step={0.5} onChange={v=>updateEcon({alternative:{...a,extraHoursPerPerson:v}})}/></div><label>Scenario evidence / uncertainty<textarea value={a.evidence} onChange={e=>updateEcon({alternative:{...a,evidence:e.target.value}})}/></label>
  <table><thead><tr><th>Projection</th><th>Current</th><th>Longer / truck alternative</th></tr></thead><tbody><tr><td>Contribution</td><td>{money(result.contributionCents)}</td><td>{money(result.contributionCents!==null&&extraContribution!==null?result.contributionCents+extraContribution:null)}</td></tr><tr><td>Per total person-hour</td><td>{money(result.perPersonHourCents)}</td><td>{money(result.contributionCents!==null&&extraContribution!==null&&altHours&&altHours>0?(result.contributionCents+extraContribution)/altHours:null)}</td></tr><tr><td>Break-even extra usable books</td><td>—</td><td>{breakEvenBooks(a.extraCostCents,econ.contributionPerBookCents)??'Unavailable'}</td></tr></tbody></table>
 </section>;
}
