"use client";
import { Save, Route, Plus } from "lucide-react";
import type { TripDraft, WorkspaceData, RouteResult, City } from "@/lib/model";
import type { Schedule } from "@/lib/planning/schedule";
import { withNights } from "@/lib/planning/draft";
import { PointFields, NumberField } from "@/components/ui/Fields";
import DayEditor from "./DayEditor";
import Timeline from "./Timeline";
import ScenarioPanel from "./ScenarioPanel";
import TripRouteMap from "@/components/map/TripRouteMap";
export default function TripPlanner({ trip, data, preview, schedule, route, onChange, onSave, onRoute, onNew, onLoad, busy, onExplore, dayIndex, onDayChange }: { trip: TripDraft; data: WorkspaceData; preview: boolean; schedule: Schedule; route: RouteResult; onChange: (t:TripDraft)=>void; onSave: ()=>void; onRoute: ()=>void; onNew:()=>void; onLoad:(t:TripDraft)=>void; busy:boolean; onExplore:(c:City)=>void; dayIndex:number; onDayChange:(i:number)=>void }) {
  const active=Math.min(dayIndex,trip.days.length-1);
  return <div className="trip-workspace"><div className="trip-main"><header className="trip-heading"><h1>{trip.name}</h1><button className="secondary-button" onClick={onNew}><Plus size={17}/>New trip</button></header>
    <div className="trip-toolbar">{preview?<a className="secondary-button" href="/sign-in">Sign in to save</a>:<button className="primary" disabled={busy} onClick={onSave}><Save size={17}/>{busy?"Saving…":"Save trip"}</button>}<button className="secondary-button" disabled={busy} onClick={onRoute}><Route size={17}/>Calculate road route</button><span className="secondary">{preview?"Unsaved reference preview":"Workspace-backed trip · revision "+trip.version}</span></div>
    <label>Trip name<input value={trip.name} onChange={e=>onChange({...trip,name:e.target.value})}/></label>
    {data.trips.length>0&&<label>Open saved trip<select value={data.trips.some(t=>t.id===trip.id)?trip.id:""} onChange={e=>{const t=data.trips.find(t=>t.id===e.target.value);if(t)onLoad(t);}}><option value="">Choose a saved trip</option>{data.trips.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
    <fieldset className="duration-picker"><legend>Trip duration</legend>{["Day trip","2 days / 1 night","3 days / 2 nights","4 days / 3 nights"].map((label,n)=><label key={n}><input type="radio" name="nights" checked={trip.nights===n} onChange={()=>{if(n<trip.nights&&trip.days.slice(n+1).some(d=>d.visits.length||d.hotel)&&!window.confirm("This removes later days and their stops from this draft. Continue?"))return;onChange(withNights(trip,n));onDayChange(0);}}/>{label}</label>)}</fieldset>
    <fieldset><legend>Crew</legend><div className="crew-options">{data.members.map(m=><label className="check-label" key={m.user_id}><input type="checkbox" checked={trip.participants.includes(m.user_id)} onChange={e=>{const people=e.target.checked?[...trip.participants,m.user_id]:trip.participants.filter(p=>p!==m.user_id);if(people.length)onChange({...trip,participants:people,transport:{...trip.transport,eligibleDrivers:Math.min(trip.transport.eligibleDrivers,people.length),driverAssignments:trip.transport.driverAssignments.filter(a=>people.includes(a.userId))}});}}/>{m.display_name}</label>)}</div><p className="secondary">Together is one shared vehicle. Solo and separate saved trips are supported; resources must not overlap.</p></fieldset>
    <div className="field-pair"><label>Return date<input type="date" value={trip.returnDate} onChange={e=>onChange({...trip,returnDate:e.target.value})}/></label><label>Hard return time ({trip.homeZone})<input type="time" value={trip.returnLocal} onChange={e=>onChange({...trip,returnLocal:e.target.value})}/></label></div>
    <details className="origin-detail"><summary>Private departure / return points {trip.origin?.confirmed?"· confirmed pin":"· approximate Affton / Lakeshire"}</summary><p className="secondary">Exact routing coordinates are sent to the provider only for an authenticated request. They are private workspace data.</p><PointFields point={trip.origin} onChange={origin=>onChange({...trip,origin})} label="Trip departure point"/><PointFields point={trip.returnPoint} onChange={returnPoint=>onChange({...trip,returnPoint})} label="Different return point (optional)"/><NumberField label="Per driving-leg contingency minutes" value={trip.driveBufferMinutes} onChange={v=>onChange({...trip,driveBufferMinutes:v??0})}/></details>
    <div className="day-tabs" role="tablist" aria-label="Trip days">{trip.days.map((d,i)=><button key={d.id} role="tab" aria-selected={active===i} onClick={()=>onDayChange(i)}>Day {i+1}<span>{d.date}</span></button>)}</div>
    <DayEditor key={trip.days[active].id} day={trip.days[active]} dayIndex={active} isLast={active===trip.days.length-1} cities={data.cities} sources={data.sources} events={data.events} onChange={next=>onChange({...trip,days:trip.days.map((d,i)=>i===active?next:d)})}/>
    <TripRouteMap trip={trip} route={route} cities={data.cities} onExplore={onExplore}/><section className="road-summary"><h3>Road route</h3><p role="status">{route.status==="available"?"Mapbox driving geometry · typical/static estimate":"Route unavailable"}</p>{route.reason&&<p>{route.reason}</p>}{route.legs.map((leg,i)=><div className="leg-row" key={i}><strong>{leg.kind} leg {i+1}</strong><span>{(leg.meters/1609.344).toFixed(1)} road miles · {Math.round(leg.seconds/60)} minutes</span></div>)}</section>
    <ScenarioPanel members={data.members} vehicles={data.vehicles} trip={trip} personHours={schedule.personHours} roadMeters={schedule.meters} onChange={onChange}/>
  </div><Timeline schedule={schedule} zone={trip.returnPoint?.zone||trip.homeZone}/></div>;
}
