import { it,expect } from 'vitest';
import { readyTrip } from '../helpers/fixtures';
import { evaluateEconomics,breakEvenBooks } from '@/lib/planning/economics';
it('separates book contribution and shared trip costs without claiming sales profit',()=>{const input=readyTrip().economics,r=evaluateEconomics(input,[10,10]);expect(r.bookContributionCents).toBe(20000);expect(r.tripCostsCents).toBe(5000);expect(r.contributionCents).toBe(15000);expect(r.perPersonHourCents).toBe(750);});
it('keeps unknown prices and yields unavailable rather than zero',()=>{const input=readyTrip().economics;input.usableBooks=null;input.costs[0].cents=null;expect(evaluateEconomics(input,null).contributionCents).toBeNull();expect(breakEvenBooks(null,100)).toBeNull();expect(breakEvenBooks(900,0)).toBeNull();expect(breakEvenBooks(901,100)).toBe(10);});
it('prevents fuel and inclusive-mileage double counting for one vehicle',()=>{const input=readyTrip().economics;input.costs.push({id:'mileage',name:'All-in mileage',cents:1000,basis:'mileage_inclusive',vehicleId:null,pricing:'fixed',centsPerMile:null});expect(evaluateEconomics(input,[10]).contributionCents).toBeNull();input.costs[1].vehicleId='30000000-0000-4000-8000-000000000002';expect(evaluateEconomics(input,[10]).errors).toEqual([]);});

it('recalculates per-mile trip costs after a route change without inventing unknown driving',()=>{const input=readyTrip().economics;input.costs[0]={...input.costs[0],pricing:'per_mile',centsPerMile:20};expect(evaluateEconomics(input,[10],16093.44).tripCostsCents).toBe(200);expect(evaluateEconomics(input,[10],32186.88).tripCostsCents).toBe(400);expect(evaluateEconomics(input,[10],null).tripCostsCents).toBeNull();});
it('matches handoff Fixture E with unchanged yield and shared cost',()=>{const e=readyTrip().economics;e.usableBooks=100;e.contributionPerBookCents=500;e.costs[0].cents=10000;const one=evaluateEconomics(e,[10]),two=evaluateEconomics(e,[10,10]);expect(one.contributionCents).toBe(40000);expect(one.perPersonHourCents).toBe(4000);expect(two.perPersonHourCents).toBe(2000);expect(two.tripCostsCents).toBe(10000);});
