import { describe,it,expect } from 'vitest';
import { readyTrip, syntheticLegs, testPoint } from '../helpers/fixtures';
import { buildSchedule,routeWaypoints } from '@/lib/planning/schedule';
import { newStop } from '@/lib/planning/draft';
import { localInstant,plusDays,minutesBetween } from '@/lib/planning/time';
import { tripConflicts,evaluateTransport } from '@/lib/planning/transport';
import { evaluateEconomics } from '@/lib/planning/economics';
import { tripSchema } from '@/lib/model';
describe('door-to-door planning using synthetic routes, not live provider verification',()=>{
 for(const n of [0,1,2,3])it('supports '+n+' nights with full rest, lodging and home return',()=>{const t=readyTrip(n),s=buildSchedule(t,syntheticLegs(t));expect(s.status).toBe('feasible');expect(t.days.length).toBe(n+1);expect(s.activities.filter(a=>a.kind==='rest')).toHaveLength(n);expect(routeWaypoints(t).at(-1)?.point.id).toBe('return-home');expect(s.personHours).toHaveLength(2);expect(s.meters).toBe((n+1)*120000);});
 it('uses one aggregate city block across multiple stores and transfers',()=>{const t=readyTrip();t.days[0].departureLocal='07:00';const v=t.days[0].visits[0],first=v.stops[0];v.stops=[{...first,minutes:80},{...first,id:crypto.randomUUID(),name:'Synthetic source B',point:testPoint('b'),minutes:80}];const s=buildSchedule(t,syntheticLegs(t,20));const city=s.activities.filter(a=>a.cityVisitId===v.id);expect(city.reduce((x,a)=>x+(a.minutes||0),0)).toBe(240);expect(city.filter(a=>a.kind==='source').reduce((x,a)=>x+a.minutes!,0)).toBe(160);});
 it('does not compress an impossible two-city day',()=>{const t=readyTrip(),v=t.days[0].visits[0];v.reservedMinutes=300;const b=structuredClone(v);b.id=crypto.randomUUID();b.cityName='Synthetic distant city';b.stops[0].id=crypto.randomUUID();t.days[0].visits.push(b);t.returnLocal='16:00';const s=buildSchedule(t,syntheticLegs(t,120));expect(s.status).toBe('infeasible');expect(s.reasons.some(r=>r.includes('deadline')||r.includes('daily limit'))).toBe(true);expect(t.days[0].visits.map(x=>x.stops[0].minutes)).toEqual([180,180]);});
 it('missing driving is unknown and never zero',()=>{const t=readyTrip(),s=buildSchedule(t);expect(s.status).toBe('provisional');expect(s.arrival).toBeNull();expect(s.elapsedHours).toBeNull();expect(s.meters).toBeNull();expect(s.activities.find(a=>a.kind==='drive')?.minutes).toBeNull();});
 it('rejects centroid-only navigation and excluded sources without a reason',()=>{const t=readyTrip();t.days[0].visits[0].stops=[];expect(()=>routeWaypoints(t)).toThrow(/actual stores/);t.days[0].visits[0].stops=[{...newStop(),category:'regular_goodwill'}];expect(buildSchedule(t).status).toBe('infeasible');expect(()=>routeWaypoints(t)).toThrow(/exception/);});
 it('preserves store duration when hours cannot fit and waits for opening',()=>{const t=readyTrip(),stop=t.days[0].visits[0].stops[0];expect(buildSchedule(t,syntheticLegs(t)).activities.some(a=>a.kind==='wait')).toBe(true);stop.windows=[{start:'2026-10-05T13:00:00Z',end:'2026-10-05T14:00:00Z'}];expect(buildSchedule(t,syntheticLegs(t)).status).toBe('infeasible');expect(stop.minutes).toBe(180);});
 it('supports one person without doubling two-person yield',()=>{const t=readyTrip(),two=buildSchedule(t,syntheticLegs(t));t.participants=t.participants.slice(0,1);const one=buildSchedule(t,syntheticLegs(t));expect(one.status).toBe('feasible');expect(one.personHours).toHaveLength(1);const e1=evaluateEconomics(t.economics,one.personHours),e2=evaluateEconomics(t.economics,two.personHours);expect(e1.contributionCents).toBe(e2.contributionCents);expect(e1.perPersonHourCents).toBe(e2.perPersonHourCents!*2);});
 it('uses the previous lodging time zone for next departure',()=>{const t=readyTrip(1);t.days[0].hotel=testPoint('eastern-hotel','America/Indiana/Indianapolis');t.days[0].checkInWindow={start:'2026-10-05T17:00:00Z',end:'2026-10-06T03:00:00Z'};const s=buildSchedule(t,syntheticLegs(t));expect(s.activities.find(a=>a.day===1)?.start).toBe('2026-10-06T10:00:00Z');});
 it('protects overnight rest and check-in windows',()=>{const t=readyTrip(1);t.days[0].restMinutes=840;t.days[0].checkInWindow={start:'2026-10-05T23:00:00Z',end:'2026-10-06T03:00:00Z'};expect(buildSchedule(t,syntheticLegs(t)).reasons.some(r=>r.includes('rest/checkout'))).toBe(true);});
 it('handles DST date changes and rejects nonexistent/ambiguous wall times',()=>{expect(plusDays('2026-10-31',1)).toBe('2026-11-01');expect(minutesBetween(localInstant('2026-10-31','06:00','America/Chicago'),localInstant('2026-11-01','06:00','America/Chicago'))).toBe(25*60);expect(()=>localInstant('2026-03-08','02:30','America/Chicago')).toThrow();expect(()=>localInstant('2026-11-01','01:30','America/Chicago')).toThrow();const t=readyTrip();t.returnDate='2026-11-01';t.returnLocal='01:30';expect(()=>buildSchedule(t,syntheticLegs(t))).not.toThrow();expect(buildSchedule(t,syntheticLegs(t)).status).toBe('infeasible');});
 it('detects person/vehicle conflicts while allowing separate resources',()=>{const t=readyTrip(),other=structuredClone(t);other.id=crypto.randomUUID();expect(tripConflicts(t,[other])).toHaveLength(1);expect(buildSchedule(t,syntheticLegs(t),tripConflicts(t,[other])).status).toBe('infeasible');other.participants=['00000000-0000-4000-8000-000000000099'];other.transport.vehicleIds=['30000000-0000-4000-8000-000000000099'];expect(tripConflicts(t,[other])).toEqual([]);});
 it('routes actual meal, lodging and rental depots in stop order',()=>{const t=readyTrip(1);t.days[0].mealPoint=testPoint('meal');t.transport={...t.transport,mode:'truck',pickup:testPoint('pickup'),returnDepot:testPoint('return')};const ids=routeWaypoints(t).map(w=>w.point.id);expect(ids[0]).toBe('home');expect(ids[1]).toBe('rental-pickup');expect(ids).toContain('meal-'+t.days[0].id);expect(ids.at(-2)).toBe('rental-return');expect(ids.at(-1)).toBe('return-home');});
 it('rejects solo destination pickup requiring two vehicles and capacity overflow',()=>{const t=readyTrip();t.transport={...t.transport,mode:'truck',destinationPickup:true,carMustReturn:true,cargoKg:700,transferPlan:'I will bring both vehicles'};const r=evaluateTransport(t.transport,1);expect(r.errors.some(e=>e.includes('Two vehicles'))).toBe(true);expect(r.errors.some(e=>e.includes('payload'))).toBe(true);expect(r.unknowns.some(e=>e.includes('clearances'))).toBe(true);});
 it('bounds invalid dates, reverse windows and duplicate IDs at input',()=>{const t=readyTrip();t.days[0].date='2026-02-30';expect(tripSchema.safeParse(t).success).toBe(false);t.days[0].date='2026-10-05';t.days[0].visits[0].stops[0].windows=[{start:'2026-10-05T15:00:00Z',end:'2026-10-05T14:00:00Z'}];expect(buildSchedule(t).status).toBe('infeasible');});
});

it('matches handoff Fixture A 16:45 arrival and Fixture B 21:30 without compressing either city',()=>{
 const t=readyTrip();t.driveBufferMinutes=0;const v=t.days[0].visits[0],template=v.stops[0];v.stops=[75,105,30].map((minutes,i)=>({...template,id:crypto.randomUUID(),point:testPoint('fixture-'+i),minutes,parkingMinutes:0,loadingMinutes:0,windows:[{start:'2026-10-05T14:00:00Z',end:'2026-10-05T23:00:00Z'}]}));
 const legs=syntheticLegs(t);legs[0].seconds=150*60;legs[1].seconds=15*60;legs[2].seconds=15*60;legs[3].seconds=150*60;
 const a=buildSchedule(t,legs);expect(a.arrival).toBe('2026-10-05T21:45:00Z');expect(a.elapsedHours).toBe(10.75);expect(a.activities.filter(x=>x.cityVisitId===v.id).reduce((sum,x)=>sum+(x.minutes||0),0)).toBe(240);
 const second=structuredClone(v);second.id=crypto.randomUUID();second.cityName='Synthetic fixture city 2';second.stops=[{...template,id:crypto.randomUUID(),point:testPoint('second'),minutes:240,parkingMinutes:0,loadingMinutes:0,windows:[{start:'2026-10-05T14:00:00Z',end:'2026-10-06T03:00:00Z'}]}];t.days[0].visits.push(second);const bLegs=syntheticLegs(t);[150,15,15,45,150].forEach((minutes,i)=>{bLegs[i].seconds=minutes*60;});const b=buildSchedule(t,bLegs);expect(b.arrival).toBe('2026-10-06T02:30:00Z');expect(b.status).toBe('infeasible');expect(b.reasons).toContain('Day 1: arrival misses the deadline by 210 minutes.');expect(second.stops[0].minutes).toBe(240);
});
it('matches handoff Fixture D time-zone crossing',()=>{const start=localInstant('2026-10-01','09:00','America/Chicago');const end=new Date(Date.parse(start)+3*3600000).toISOString();expect(new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'America/Indiana/Indianapolis'}).format(new Date(end))).toBe('13:00');});
